#! /bin/bash

echo "unzip files of Required Packages"
UNTAR="tar xvzf"
UNZIP="unzip "
LOCATIONS="/home/jsgene/Python_packages/"
TARGZ=".tar.gz"

$UNTAR $LOCATIONS"urllib3-1.21.1"$TARGZ;
$UNTAR $LOCATIONS"pbr-3.1.1"$TARGZ;
$UNTAR $LOCATIONS"Counter-1.0.0"$TARGZ;
$UNTAR $LOCATIONS"certifi-2017.4.17"$TARGZ;
$UNTAR $LOCATIONS"argparse-1.4.0"$TARGZ;
$UNTAR $LOCATIONS"Cython-0.25.2"$TARGZ;
$UNTAR $LOCATIONS"six-1.10.0"$TARGZ;
$UNTAR $LOCATIONS"pyparsing-2.2.0"$TARGZ;
$UNTAR $LOCATIONS"packaging-16.8"$TARGZ;
$UNTAR $LOCATIONS"chardet-3.0.4"$TARGZ;
$UNTAR $LOCATIONS"appdirs-1.4.3"$TARGZ;
$UNTAR $LOCATIONS"future-0.16.0"$TARGZ;
$UNTAR $LOCATIONS"pbs-python-4.4.2.1"$TARGZ;
$UNTAR $LOCATIONS"traceback2-1.4.0"$TARGZ;
$UNTAR $LOCATIONS"linecache2-1.0.0"$TARGZ;
$UNTAR $LOCATIONS"unittest2-1.1.0"$TARGZ;
$UNTAR $LOCATIONS"wheel-0.30.0a0"$TARGZ;
$UNTAR $LOCATIONS"wgetter-0.6"$TARGZ;
$UNTAR $LOCATIONS"ordereddict-1.1"$TARGZ;
$UNTAR $LOCATIONS"idna-2.5"$TARGZ;
$UNTAR $LOCATIONS"numpy-1.13.0"$TARGZ;
$UNTAR $LOCATIONS"pytz-2017.2"$TARGZ;
$UNTAR $LOCATIONS"python-dateutil-2.6.0"$TARGZ;
$UNTAR $LOCATIONS"pandas-0.20.2"$TARGZ;
$UNTAR $LOCATIONS"sphinxcontrib-websupport-1.0.1"$TARGZ;
$UNTAR $LOCATIONS"imagesize-0.7.1"$TARGZ;
$UNTAR $LOCATIONS"alabaster-0.7.10"$TARGZ;
$UNTAR $LOCATIONS"Babel-2.4.0"$TARGZ;
$UNTAR $LOCATIONS"snowballstemmer-1.2.1"$TARGZ;
$UNTAR $LOCATIONS"docutils-0.14rc1"$TARGZ;
$UNTAR $LOCATIONS"MarkupSafe-1.0"$TARGZ;
$UNTAR $LOCATIONS"Jinja2-2.9.6"$TARGZ;
$UNTAR $LOCATIONS"Sphinx-1.6.2"$TARGZ;
$UNTAR $LOCATIONS"scipy-0.19.1"$TARGZ;
$UNTAR $LOCATIONS"cycler-0.10.0"$TARGZ;
$UNTAR $LOCATIONS"matplotlib-2.0.2"$TARGZ;
$UNTAR $LOCATIONS"matplotlib-venn-0.11.5"$TARGZ
